# Generated by Django 4.2 on 2023-04-30 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_amount', models.FloatField()),
                ('return_amount', models.FloatField()),
                ('trans_time', models.DateTimeField()),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending_machine.beverage')),
            ],
        ),
    ]
